### ISSUE TITLE
error

### ISSUE THREAD

**Issue by conheaven** [JunnanDong/Localized-MiniGPT4#1]
Traceback (most recent call last):
  File "/home/khw/vlm/MiniGPT-4/demo_localized.py", line 13, in <module>
    from minigpt4.conversation.conversation import Chat, CONV_VISION
ImportError: cannot import name 'CONV_VISION' from 'minigpt4.conversation.conversation' (/home/khw/vlm/MiniGPT-4/minigpt4/conversation/conversation.py)

**Comment by conheaven** [comment]
you need to change the 'CONV_VISION' to 'CONV_VISION_Vicuna0' or 'CONV_VISION_LLama2' or 'CONV_VISION_minigptv2'

**Comment by JunnanDong** [comment]
> you need to change the 'CONV_VISION' to 'CONV_VISION_Vicuna0' or 'CONV_VISION_LLama2' or 'CONV_VISION_minigptv2'

Thanks. I suppose it's due the new update in the latest MiniGPT-4 model file.
